= About illumos-zonemgr

This repo holds the script to manage illumos zones lifecycle for essentially
disposable zones that are clones of a golden build env, which has its own
update schedule.

The initial intended use-case is management of dedicated single-use build
environments with just enough tools and prerequisites installed for compilation
of the illumos-gate and userland stacks (including disposable zones with just
the minimal set of known tools and prerequisites for a single component build).

----
This file and its contents are supplied under the terms of the
Common Development and Distribution License ("CDDL"). You may
only use this file in accordance with the terms of the CDDL.

A full copy of the text of the CDDL should have accompanied this
source. A copy of the CDDL is also available via the Internet at
http://www.illumos.org/license/CDDL.

Copyright 2016-2017, Jim Klimov. All rights reserved.
----

== Terminology

Common definitions (from the Solarish ecosystem):

* *Boot Environment* (*BE*) -- a filesystem with contents sufficient to
  instantiate a fully-fledged usable system for a given architecture and
  environment (e.g. kernel and drivers may be missing in a BE for lightweight
  virtualization container).
* *Global zone* (*GZ*) -- the "physically installed" illumos-based distro in
  a barebone or VM computer, running a kernel and interfacing with hardware.
* *Local Zone* or *Non-Global Zone* (*LZ* or *NGZ*) -- a container running in
  the same kernel as the GZ, providing a lightweight virtualized environment
  (with individual root filesystem, networking stack, process and user-account
  spaces) orchestrated by the GZ. If there is any resource sharing with other
  environments (e.g. access to common filesystems) -- then it is intentionally
  done by the setup in the GZ, and/or by general approach to shared resources
  (usually via net -- e.g. NFS, LDAP, etc.)
* *Operating Environment* (*OE*) -- a BE, such as the GZ or LZ root filesystems
  or an installation/recovery miniroot, and the actual instance of an operating
  system running over such a filesystem.

Local definitions (introduced by this project):

* *Golden Image* (*GI*) zone -- a local zone prepared in advance that contains
  minimal systems setup and a defined set of packages, and that is not intended
  for direct booting -- but rather for snapshotting and cloning into applied
  deployments. The workflow below considers golden-image zones created from
  scratch and from snapshots of earlier (more generic) GI zones.
* *Disposable Zone* (*DZ*) -- a clone of some particular golden-image zone which
  is intended to persist while running some time-limited task (e.g. a build)
  possibly with more specific resources designated to fulfill this job, and
  to be destroyed afterwards.

== Expected workflow

All of the below assumes RBAC privileges sufficient to create, manage and
destroy local zones and datasets (e.g. a "Primary Admin") via `pfexec`.

* Slurp script configs (hardcoded defaults; system, user level and command-line
  passed config file overrides) -- e.g. container root datasets
* Zone-creation task stack:
** Create the golden-image containment dataset if missing yet
*** Disable auto-snaps
*** Enable strong compression
*** Enable dedup?
** Create the golden-image zone from scratch, if the name is not yet occupied:
*** Let specify image template type (linked, brand, etc.) to set up the config
*** Minimal config zone-wise (no resources, filesystem/dataset provisions,
    networking, user accounts...); set autoboot:=false
*** Let specify package source(s) -- URL to IPS repo, possibly just one
    publisher may be allowed for initial installation, but more may be added
    after initial "image" setup
*** Consider packaging, tarballs, zfs-send images...
** Create a golden-image zone from existing golden-image zone (clone current
   state, last or specified snapshot):
*** Add metadata (zonecfg field?) to track which GI this image was built from
*** Specify package(s) to remove from the zone compared to original while
    creating it (e.g. to avoid conflicts for subsequently added packages)
*** Specify package(s) to add into the zone compared to original while creating
*** Same limitations (e.g. simplicity) as above
** Create the disposable-zone containment dataset if missing yet:
*** Disable auto-snaps
*** Enable moderate or no compression
*** Disable dedup
** Create a disposable zone from specified golden-image zone (clone current
   state, last or specified snapshot):
*** Add resource definitions (datasets/lofs, network, user accounts/ldap, ...)
*** Script cloning of file-based user/shadow and group account data from GZ
    to LZ for respective specified accounts
* General maintenance actions:
** iterate all golden-image zones to upgrade them (e.g. from crontab)
* General actions against any managed zones (GI or DZ):
** generate a unique name-part for the zone (hash of concat of sorted requested
   pkg names?) that may get prefixed and/or suffixed for GI and DZ instances
** snapshot a zone
** clone a zone (clone current state, last or specified snapshot)
** pkg-update contents of a (golden-image?) zone, snapshot after success
** install specified package(s) into the named zone, snapshot after success
** start, stop a zone
** destroy a zone (including config)
** halt and roll back to specified snapshot (e.g. reuse same)
** run a command inside the zone (via zlogin), maybe as a specified account

